HealthCareSys/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^',include('accounts.urls')),
    url(r'^accounts/',include('accounts.urls')),
    # url(r'^', include(('account.urls','account' ), namespace='healthcare')),
    url(r'^', include(('healthcare.urls','healthcare' ), namespace='healthcare')),
    
]

accounts/urls.py
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    url(r'^updateuser/$', views.UserFormUpdate.as_view(), name='userupdate'),
    #url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^user/(?P<pk>[0-9]+)/', views.UserDetail.as_view(), name='user-detail'),
    url(r'^doctor/(?P<pk>[0-9]+)/', views.DoctorDetail.as_view(), name='doctor-detail'),
    url(r'^home/$', views.UserFormView.as_view(), name='home'),
    url(r'^login/$', views.LoginFormView.as_view(), name='login'),
    path('logout/',
    auth_views.LogoutView.as_view(
        template_name=None,
        next_page='/'
    ),
    name = 'logout'
)
]

healthcare/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views

app_name = 'healthcare'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^appointment/$', views.AppointmentCreate.as_view(), name='book-appointment'),
    url(r'^appointment/(?P<pk>[0-9]+)/', views.AppointmentDetail.as_view(), name='appointment-detail'),
    url(r'^edit-appointment/(?P<pk>[0-9]+)/$', views.AppointmentUpdate.as_view(), name='appointment-update'),
    url(r'^transactions/$', views.TransactionListView.as_view(), name='transactions'),
    url(r'^transaction/(?P<pk>[0-9]+)/', views.TransactionDetail.as_view(), name='transaction-detail'),
    url(r'^search/', views.search, name='search'),
    url(r'^advice/', views.advice, name='advice'),
    url(r'^BMI/', views.BMI, name='BMI'),
    url(r'^BMR/', views.BMR, name='BMR'),
    url(r'^WHR/', views.WHR, name='WHR'),
    url(r'^PRG/', views.PRG, name='PRG'),
    url(r'^print/', views.print_report, name='print'),
]

healthcare/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import datetime 
from accounts.models import DoctorProfile
from django.urls import reverse
from django.db import transaction

class Location(models.Model):
    location_id = models.AutoField(primary_key=True)
    location_name = models.CharField(max_length=500)

    def __str__(self):
        return self.location_name
 
class Hospital(models.Model):
    name = models.CharField(max_length=100)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    contact = models.CharField(max_length=100, default='123456789')
    email = models.CharField(max_length=100,default='hospital_email@gmail.com')
    amount = models.PositiveIntegerField(default=100)

    def __str__(self):
        return self.name

class Department(models.Model):
    department_id = models.AutoField(primary_key=True)
    department_name = models.CharField(max_length=500)

    def __str__(self):
        return self.department_name

class Transaction(models.Model):
    from_user = models.ForeignKey(User, related_name='from_user', on_delete=models.CASCADE)
    to_user = models.ForeignKey(User, related_name='to_user', on_delete=models.CASCADE)
    time = models.DateTimeField(default=datetime.now)
    amount = models.PositiveIntegerField()
    reason = models.CharField(max_length=100)
    success = models.BooleanField(default=False)

    @transaction.atomic
    def make_transaction(self,from_user, to_user, amount, reason):
        status = False
        if from_user.amount >= amount:
            from_user.amount -= amount
            to_user.amount += amount
            from_user.save()
            to_user.save()
            status = True
        transaction = Transaction(from_user=from_user.user, to_user=to_user.user, amount=amount, success=status, reason=reason)
        transaction.save()
        return transaction, status

    def get_absolute_url(self):
        return reverse('healthcare:transaction-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.id) + ': ' + str(self.from_user) + ' to ' + str(self.to_user) + ' - ' + str(self.amount)



class Appointment(models.Model):
    STATUS = (
        ('Unconfirmed', 'Unconfirmed'),
        ('Confirmed', 'Confirmed'),
    )
    appointment_id = models.AutoField(primary_key=True)
    transaction_id = models.ForeignKey(Transaction, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    doctor = models.ForeignKey(DoctorProfile, on_delete=models.CASCADE)
    booking_time = models.DateTimeField(default=datetime.now)
    appointment_date = models.DateField()
    appointment_time = models.TimeField(blank=True, null=True)
    prescription = models.TextField(default='Prescription will be filled by the doctor.')
    status = models.CharField(max_length=20, default='Unconfirmed', choices=STATUS)
    fee = models.PositiveIntegerField(default=500)

    def get_absolute_url(self):
        return reverse('healthcare:appointment-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return str(self.appointment_id) + ': ' + self.user.username + ' - ' + self.doctor.user.username


        

healthcare/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Appointment
from django.forms.widgets import DateInput

class AppointmentForm(forms.ModelForm):

    class Meta:
        model = Appointment
        fields = ['doctor', 'appointment_date']
        widgets = {
            'appointment_date': forms.DateInput(attrs={
            'type':'date'})
        }
            

healthcare/views.py
from django.http.response import JsonResponse
from django.shortcuts import render, redirect
from django.views.generic import View
from .models import Hospital, Appointment, Location, Department, Transaction
from accounts.models import DoctorProfile
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.forms.widgets import DateInput
from .forms import AppointmentForm
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.db.models import Q
from datetime import datetime
from django.core.mail import EmailMessage
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from .resources import AppointmentResource, TransactionResource
from .preg import function

def index(request):
    return render(request, 'healthcare/home.html')

def advice(request):
    return render(request, 'healthcare/advice.html')



def BMI(request):
    
    height = request.POST.get('height')
    weight= request.POST.get('weight')
    BMI = int(weight) / (int(height)/100)**2
    context = {'BMI': BMI}
    return JsonResponse(context)

def BMR(request):
    
    height = request.POST.get('height')
    weight= request.POST.get('weight')
    age = request.POST.get('age')
    gender= request.POST.get('gender')
    if gender == 'male':
        bmr = 13.7 * int(weight) + 5.0 * int(height) - 6.8 * int(age) + 66
    elif gender == 'female':
        bmr = 9.6 * int(weight) + 1.8 * int(height) - 4.7 * int(age) + 655
    else:
        bmr = -1
 
    context = {'BMR': bmr}
    return JsonResponse(context)

def WHR(request):
    
    height = request.POST.get('height')
    weight= request.POST.get('weight')
    # age = request.POST.get('age')
    gender= request.POST.get('gender')
    bmr = int(weight)/int(height)
    
    context = {'WHR': bmr}
    return JsonResponse(context)

def PRG(request):
    
    monthh = request.POST.get('height')
    dayy= request.POST.get('weight')
    print(monthh, dayy)
    
    context = {'WHR': function(monthh, int(dayy))}
    return JsonResponse(context)

def search(request):
    print("yes")
    locations = Location.objects.all().order_by('location_name')
    departments = Department.objects.all().order_by('department_name')
    if not request.GET.get('location', 'none') == 'none' and not request.GET.get('specialty', 'none') == 'none':
        location = request.GET['location']
        specialty = request.GET['specialty']
        location = Location.objects.filter(location_name=location)
        hospitals = Hospital.objects.filter(location=location)
        doctors = []
        for hospital in hospitals:
            specialty = Department.objects.filter(department_name=specialty)
            doctors += DoctorProfile.objects.filter(hospital=hospital, specialization=specialty)

        return render(request, 'healthcare/search.html', {'doctors': doctors, 'locations': locations, 'departments': departments})

    return render(request, 'healthcare/search.html', {'locations': locations, 'departments': departments})

def print_report(request):
    if request.user.is_superuser:
        if request.GET.get('data', 'none') == 'appointments':
            appointment_resource = AppointmentResource()
            dataset = appointment_resource.export()
            response = HttpResponse(dataset.csv, content_type='text/csv')
            response['Content-Disposition'] = 'attachment; filename="appointments.csv"'
            return response
        elif request.GET.get('data', 'none') == 'transactions':
            transaction_resource = TransactionResource()
            dataset = transaction_resource.export()
            response = HttpResponse(dataset.csv, content_type='text/csv')
            response['Content-Disposition'] = 'attachment; filename="transactions.csv"'
            return response
    return redirect('/')
            

def export(request):
    person_resource = PersonResource()
    dataset = person_resource.export()
    response = HttpResponse(dataset.csv, content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="persons.csv"'
    return response

@method_decorator(login_required, name='dispatch')
class AppointmentCreate(CreateView):
    form_class = AppointmentForm
    template_name = 'healthcare/appointment_form.html'
    doctor = None

    def send_email(self, transaction):
        try:
            subject = "Invoice for Transaction %d" % transaction.id
            body = """
Greetings %s %s!
You've recently carried out a transaction on HealthCareSys. Here are the details for future reference:-

Transaction ID: %d
From: %s
To: %s
Amount: %d
DateTime: %s
Success: %s

Wishing you the best of health,
Team HealthCareSys.
""" % (transaction.from_user.first_name, transaction.from_user.last_name, transaction.id, transaction.from_user.username, transaction.to_user.username, transaction.amount, transaction.time, transaction.success)
            email = EmailMessage(subject, body, to=[transaction.from_user.email])
            email.send()
        except:
            print("Unable to send email (%s)" % transaction.from_user.email)
    def get_initial(self):
        if self.request.GET.get('doctor_id') and DoctorProfile.objects.filter(id=self.request.GET['doctor_id']):
            return { 'doctor': DoctorProfile.objects.get(id=self.request.GET['doctor_id'])}
    
    def form_valid(self, form):
        appointment = form.save(commit=False)
        appointment.user = self.request.user
        appointment.fee = appointment.doctor.consultation_fee
        
        transaction = Transaction()
        transaction, success = transaction.make_transaction(from_user=self.request.user.userprofile, to_user=appointment.doctor, amount=appointment.fee, reason="Book Appointment")
        if success:
            appointment.transaction_id = transaction
            appointment.save()
        else:
            print('Transaction %d failed' % transaction.id)
        self.send_email(transaction)
        return redirect('healthcare:index')

@method_decorator(login_required, name='dispatch')
class AppointmentUpdate(UpdateView):
    model = Appointment
    template_name = 'healthcare/appointment_update.html'        

    def dispatch(self, request, *args, **kwargs):
        if hasattr(request.user, 'doctorprofile'):
            self.fields = ['appointment_time', 'status', 'prescription']
        else:
            self.fields = ['appointment_date']
        return super(AppointmentUpdate,self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        appointment = form.save(commit=False)
        if hasattr(self.request.user, 'userprofile'):
            appointment.status = 'Unconfirmed'
            appointment.appointment_time = None
        appointment.save() 
        return redirect(self.get_success_url())

    
    
class IndexView(generic.ListView):
    template_name = 'healthcare/home.html'
    context_object_name = 'appointments'

    
    def get_queryset(self):
        if self.request.user.is_authenticated:
            if hasattr(self.request.user, 'userprofile'):
                return Appointment.objects.filter(user=self.request.user)
            elif hasattr(self.request.user, 'doctorprofile'):
                return Appointment.objects.filter(doctor=self.request.user.doctorprofile)
            
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)   
         
        appointments=[]
        past_appointments =[]

        upcoming_appointments = []

        if hasattr(self.request.user, 'userprofile'):
            appointments=Appointment.objects.filter(user=self.request.user)
        elif hasattr(self.request.user, 'doctorprofile'):
            appointments=Appointment.objects.filter(doctor=self.request.user.doctorprofile)
        elif (self.request.user.is_superuser):
            appointments = Appointment.objects.all()

        for appointment in appointments:
            x=datetime.combine(appointment.appointment_date,datetime.min.time())
            z=datetime.now()
            if  x < z:
                past_appointments += [appointment]
            else:
                upcoming_appointments += [appointment]
        
        context['past_appointments'] = past_appointments
        
        context['upcoming_appointments'] = upcoming_appointments
        
        return context


class AppointmentDetail(generic.DetailView):
    model = Appointment
    template_name = 'healthcare/appointment.html'

class TransactionListView(generic.ListView):
    template_name = 'healthcare/transactions.html'
    context_object_name = 'transactions'

    def get_queryset(self):
        if self.request.user.is_superuser:
            return Transaction.objects.all()
        elif self.request.user.is_authenticated():
            return Transaction.objects.filter(Q(from_user=self.request.user) | Q(to_user=self.request.user))

class TransactionDetail(generic.DetailView):
    model = Transaction
    template_name = 'healthcare/transaction-detail.html'

healthcare/templates/includes/_scripts.html
<!-- jQuery library -->

{% load static %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>


            $(document).on('submit', '#BMIform', function(e){
              e.preventDefault();
              var texter = "Your BMI is ";
              $('#submitBMI').hide();
              $('#my_loadBMI').show();
              console.log($('#widthBMI').val());
              $.ajax({
                type: 'POST',
                url: '{% url 'healthcare:BMI' %}',
                data:{
                  height: $('#widthBMI').val(),
                  weight:$('#heightBMI').val(),
                  csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                },
                
                success:function(response){
                  
                  console.log(response.BMI);
                  $('#BMIresult').text(texter + response.BMI);
                  $('#submitBMI').show();
                $('#my_loadBMI').hide();
                },
                error: function(data) {
                  $('#Notifications').html(data.message).css('color', 'red');
                    $('#submitBMI').show();
                $('#my_loadBMI').hide();
                }
              });
            });

            
            $(document).on('submit', '#BMRform', function(e){
              e.preventDefault();
              var texter = "Your BMR is ";
              $('#submitBMR').hide();
              $('#my_loadBMR').show();
              console.log($('#genderBMR').val());
              $.ajax({
                type: 'POST',
                url: '{% url 'healthcare:BMR' %}',
                data:{
                  height: $('#widthBMR').val(),
                  weight:$('#heightBMR').val(),
                  gender: $('#genderBMR').val(),
                  age:$('#ageBMR').val(),
                  csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                },
                
                success:function(response){
                  
                  console.log(response.BMR);
                  $('#BMRresult').text(texter + response.BMR);
                  $('#submitBMR').show();
                $('#my_loadBMR').hide();
                },
                error: function(data) {
                  $('#Notifications').html(data.message).css('color', 'red');
                    $('#submitBMR').show();
                $('#my_loadBMR').hide();
                }
              });
            });

                   
            $(document).on('submit', '#WHRform', function(e){
              e.preventDefault();
              var texter = "Your WHR is ";
              $('#submitWHR').hide();
              $('#my_loadWHR').show();
              console.log($('#genderWHR').val());
              var gender = $('#genderWHR').val()
              $.ajax({
                type: 'POST',
                url: '{% url 'healthcare:WHR' %}',
                data:{
                  height: $('#widthWHR').val(),
                  weight:$('#heightWHR').val(),
                  gender: $('#genderWHR').val(),
                 
                  csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                },
                
                success:function(response){
                  
                  console.log(response.WHR);
                  if(response.WHR < 1){
                    console.log("true")
                  }
                  if(gender=="male"){
                    console.log('malego')
                    if(response.WHR <= 1){
                        $('#WHRresult').text('Your have a normal waist male to hip ratio of ' + response.WHR).css('color', 'green');
                        $('#submitWHR').show();
                        $('#my_loadWHR').hide();
                      }else{
                        $('#WHRresult').text('Your have a abnormal male waist to hip ratio of ' + response.WHR).css('color', 'red');
                        $('#submitWHR').show();
                        $('#my_loadWHR').hide();
                      }

                  }
                  if(gender=="female"){
                    if(response.WHR <= 0.85){
                        $('#WHRresult').text('Your have a normal female waist to hip ratio of ' + response.WHR).css('color', 'green');
                        $('#submitWHR').show();
                        $('#my_loadWHR').hide();
                      }else{
                        $('#WHRresult').text('Your have a abnormal female waist to hip ratio of ' + response.WHR).css('color', 'red');
                        $('#submitWHR').show();
                        $('#my_loadWHR').hide();
                      }

                  }

                  
                },
                error: function(data) {
                  $('#Notifications').html(data.message).css('color', 'red');
                    $('#submitWHR').show();
                $('#my_loadWHR').hide();
                }
              });
            });

            $(document).on('submit', '#PRGform', function(e){
              e.preventDefault();
              var texter = "Your PRG is ";
              $('#submitPRG').hide();
              $('#my_loadPRG').show();
              console.log($('#genderPRG').val());
              var gender = $('#genderPRG').val()
              $.ajax({
                type: 'POST',
                url: '{% url 'healthcare:PRG' %}',
                data:{
                  height: $('#month').val(),
                  weight:$('#heightPRG').val(),
                  
                 
                  csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                },
                
                success:function(response){
                  
                  console.log(response.PRG);
                  $('#PRGresult').text(response.WHR).css('color', 'green');
                   $('#submitPRG').show();
                  $('#my_loadPRG').hide();
                  
                },
                error: function(data) {
                  $('#Notifications').html(data.message).css('color', 'red');
                    $('#submitPRG').show();
                $('#my_loadPRG').hide();
                }
              });
            });
            
</script>

<script>
$(document).ready(function() {
  const monthNames = ["January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
  ];
 
  let selectMonth = $("#month");
 


  for (var m = 0; m < 12; m++) {
    let month = monthNames[m];
    let monthElem = document.createElement("option");
    monthElem.value = month;
    monthElem.textContent = month;
    selectMonth.append(monthElem);
  }

});
</script>